version: '3.9'

services:
  django:
    build:
      context: ./shorts/
      dockerfile: ./Dockerfile
    container_name: django
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./shorts:/code/
    ports:
      - 8000:8000
    restart: always

  redis:
    image: redis:7.2.4-alpine3.19
    container_name: redis
    restart: always

  celery:
    build:
      context: ./shorts/
      dockerfile: ./Dockerfile
    container_name: celery
    command: >
      sh -c "celery -A shorts worker -l INFO"
    volumes:
      - ./shorts:/code/
